- name: set up nginx
  hosts: web
  tasks:
    - name: install nginx on rhel
      become: yes
      yum:
        name: epel-release
        state: present
    - name: install nginx on rhel
      become: yes
      yum:
        name: nginx
        state: present
    - name: copy index.html
      become: yes
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
    - name: start nginx
      become: yes
      service:
        name: nginx
        state: started