---
- name: Ornek Playbook 001
  hosts: all
  vars:
    myvar: "Ornek Playbook"
    mybool: false
    mycities:
      - Ankara
      - Istanbul

  tasks:
    - name: degisken yazdir
      ansible.builtin.debug:
        msg: "value {{ myvar }}"
      notify: reload

    - name: kosullu ifade
      ansible.builtin.debug:
        msg: "kosullu ifade icin ornek mesaj"
      when: mybool

    - name: sehirleri yazdir
      ansible.builtin.debug:
        var: item
      loop: "{{ mycities }}"

  handlers:
    - name: reload
      ansible.builtin.debug:
        msg: "example handler"
