---
- name: Debug Module
  hosts: all
  vars:
    fruit: "elma"
  tasks:
    - name: debug message
      ansible.builtin.debug:
        msg: "Bu bir {{ fruit }} mesaji"
        verbosity: 2
    - name: debug message 02
      ansible.builtin.debug:
        msg: "Merhaba Ansible"
        verbosity: 2

