- name: set up nginx
  hosts: web
  #gather_facts: no
  tasks:
    - name: install nginx on rhel
      become: yes
      yum:
        name: epel-release
        state: present
    - name: install nginx on rhel
      become: yes
      yum:
        name: nginx
        state: present
    - name: copy index.html
      become: yes
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
    - name: start nginx
      become: yes
      service:
        name: nginx
        state: started
    - name: set fact 
      set_fact:
        my_fact:
          - 10
          - 20
    - name: debug
      debug:
        var: my_fact